create table crew_members (
    crew_id bigint not null,
    member_id bigint not null,
    primary key (crew_id, member_id)
);

create table crews (
    invite_code varchar(6) not null unique,
    created_at timestamp(6) not null,
    created_by bigint not null,
    id bigint generated by default as identity,
    name varchar(50) not null,
    cover_image varchar(255),
    primary key (id)
);

create table members (
    deleted_at timestamp(6),
    id bigint generated by default as identity,
    bio varchar(100),
    email varchar(255),
    nickname varchar(255) not null,
    profile_image varchar(255),
    provider varchar(255) not null check (provider in ('GOOGLE','KAKAO','APPLE')),
    provider_id varchar(255) not null,
    primary key (id),
    unique (provider, provider_id)
);

create table pin_images (
    pin_id bigint not null,
    image_url varchar(255) not null
);

create table pin_splits (
    amount bigint not null,
    pin_id bigint not null,
    user_id bigint not null
);

create table pins (
    amount bigint not null,
    author_id bigint not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    paid_by bigint not null,
    play_id bigint not null,
    title varchar(100) not null,
    location varchar(200),
    memo varchar(500),
    category varchar(255) not null check (category in ('FOOD','CAFE','SHOPPING','TRANSPORT','STAY','ACTIVITY','ETC')),
    settlement_type varchar(255) not null check (settlement_type in ('EQUAL','CUSTOM')),
    primary key (id)
);

create table play_members (
    member_id bigint not null,
    play_id bigint not null,
    primary key (member_id, play_id)
);

create table play_regions (
    play_id bigint not null,
    region varchar(255) not null
);

create table play_tags (
    play_id bigint not null,
    tag varchar(255) not null
);

create table plays (
    end_date date,
    start_date date not null,
    created_at timestamp(6) not null,
    created_by bigint not null,
    crew_id bigint not null,
    id bigint generated by default as identity,
    settled_at timestamp(6),
    title varchar(100) not null,
    cover_image varchar(255),
    type varchar(255) not null check (type in ('TRAVEL','DATE','HANGOUT','DAILY','ETC')),
    primary key (id)
);

create table refresh_tokens (
    expires_at timestamp(6) not null,
    id bigint generated by default as identity,
    member_id bigint not null,
    token varchar(255) not null unique,
    primary key (id)
);

alter table crew_members
    add constraint fk_crew_members_crew foreign key (crew_id) references crews;

alter table pin_images
    add constraint fk_pin_images_pin foreign key (pin_id) references pins;

alter table pin_splits
    add constraint fk_pin_splits_pin foreign key (pin_id) references pins;

alter table play_members
    add constraint fk_play_members_play foreign key (play_id) references plays;

alter table play_regions
    add constraint fk_play_regions_play foreign key (play_id) references plays;

alter table play_tags
    add constraint fk_play_tags_play foreign key (play_id) references plays;
