create table pin_transfer_marks (
    id bigint generated by default as identity,
    pin_id bigint not null,
    from_member_id bigint not null,
    to_member_id bigint not null,
    sent_at timestamp(6),
    received_at timestamp(6),
    primary key (id),
    constraint uk_pin_transfer_marks_pin_from_to unique (pin_id, from_member_id, to_member_id)
);

alter table pin_transfer_marks
    add constraint fk_pin_transfer_marks_pin foreign key (pin_id) references pins on delete cascade;

create index ix_pin_transfer_marks_pin_id on pin_transfer_marks (pin_id);
