create table activity_logs (
    id bigint generated by default as identity,
    crew_id bigint not null,
    actor_member_id bigint,
    type varchar(40) not null,
    payload text,
    created_at timestamp(6) not null,
    primary key (id)
);

alter table activity_logs
    add constraint fk_activity_logs_crew foreign key (crew_id) references crews on delete cascade;

create index ix_activity_logs_crew_created on activity_logs (crew_id, created_at);
